In [1]:
def findingTop(board,col):
    if col<(board.shape[1]):
        lc = board.shape[0] -1
        if board[(lc)][col] == "O" : return lc 
        else :
            while board[lc][col] != "O":
                lc = lc-1
                if lc < 0 : 
                    break
            return lc
    else:
        return -1

In [2]:
def printerOutput(board,symbol_O,symbol_1,symbol_2):
    
    rows = board.shape[0]
    cols = board.shape[1]
    
    
    for i in range(rows):
        for j in range(cols):
            if board[i][j] == "O" : board[i][j] = symbol_O
            if board[i][j] == "1" : board[i][j] = symbol_1
            if board[i][j] == "2" : board[i][j] = symbol_2
    
    
    
    for i in range(rows):
        for j in range(cols):
            if j == 0 : print("| ", end=' ')
            print(board[i][j]," | ", end=' ')
        print(" ")
#         print("\n")
    print("-------------------------------------------")
    print("  ",end=' ')
    for i in range(cols):
        print(i,"   ",end =" ")
        
        
    for i in range(rows):
        for j in range(cols):
            if board[i][j] == symbol_O : board[i][j] = "O"
            if board[i][j] == symbol_1 : board[i][j] = "1"
            if board[i][j] == symbol_2 : board[i][j] = "2"

In [3]:
def checkInput(board,col):
    cursor = findingTop(board,col)
    if cursor != -1:
        return True
    else: 
        return False

In [12]:
def checkWinner(board,symbol_O,symbol_1,symbol_2):
    
    symbol_1 = "\u25CF"
    symbol_2 = "\u2717"
    
    rows = board.shape[0]
    cols = board.shape[1]

    board2 = board[::-1,:]
    rows2 = board2.shape[0]
    cols2 = board2.shape[1]

    row_list = []
    col_list = []
    diag1_list = []
    diag2_list = []


    for i in range(rows):
        rr=[]
        result = ""
        for j in range(cols):
            rr.append(board[i][j])
        for k in rr:
            result = result + str(k)
        row_list.append(result)



    for i in range(cols):
        cc=[]
        result = ""
        for j in range(rows):
            cc.append(board[j][i])
        for k in cc:
            result = result + str(k)
        col_list.append(result)



    for i in range(3-cols,cols-3):
        dd = []
        result = ""
        dd.append(np.diag(board, k = i))
        for j in dd:
            result = result + str(j)
        result = result.replace("'", '')
        result = result.replace(" ","")
        result = result.replace("[","")
        result = result.replace("]","")
        diag1_list.append(result)  



    for i in range(3-cols2,cols2-3):
        dd = []
        result = ""
        dd.append(np.diag(board2, k = i))
        for j in dd:
            result = result + str(j)
        result = result.replace("'", '')
        result = result.replace(" ","")
        result = result.replace("[","")
        result = result.replace("]","")
        diag2_list.append(result)

    term_1= "1111"
    winner1 = "\nPlayer 1" + symbol_1 + " is Winner"

    for i in row_list:
        if term_1 in i :
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner1)
            return True
    for i in col_list:
        if term_1 in i :
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner1)
            return True
    for i in diag1_list:
        if term_1 in i :
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner1)
            return True
    for i in diag2_list:
        if term_1 in i : 
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner1)
            return True

    term_2= "2222"
    winner2 = "\nPlayer 2" + symbol_2 + " is Winner"

    for i in row_list:
        if term_2 in i : 
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner2)
            return True
    for i in col_list:
        if term_2 in i : 
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner2)
            return True
    for i in diag1_list:
        if term_2 in i : 
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner2)
            return True
    for i in diag2_list:
        if term_2 in i : 
            printerOutput(board,symbol_O,symbol_1,symbol_2)
            print(winner2)
            return True
    i = board.shape[1]-1
#     while i < range(board.shape[1]):
#         if "O" not in board[i]:
#             i = i-1
#             if i < 0:
#                 printerOutput(board,symbol_O,symbol_1,symbol_2)
#                 print('\nDraw')
#                 return True

In [8]:
# import numpy as np


    
# boardo = np.array([["4","5","6","7"],
#                    ["2","O","6","9"],
#                    ["6","8","3","0"]])

# for col in range(boardo.shape[1]):
# #     print(boardo[:,col])
#     if "O" not in boardo[col]:
#         print("Yess!")
# #     else: print("NO!")

# # print(board)
# # for i in range(board[] :
# #         if "O" not in board[i]:
# #             i = i + 1
# #             if i > board[0]:
# #                 printerOutput(board,symbol_O,symbol_1,symbol_2)
# #                 print('\nDraw')
# #                 return True

In [14]:
import numpy as np

# board = np.array([["1","2","1","4","O","O","O"],
#                   ["2","3","4","5","O","4","4"],
#                   ["3","2","9","6","8","3","3"],
#                   ["1","5","7","8","9","1","3"],
#                   ["5","8","7","9","6","5","5"],
#                   ["9","7","7","8","5","2","4"]])
# board = np.array([["O","O","O","O","O","O","O"],
#                   ["O","O","O","O","O","O","O"],
#                   ["O","O","O","O","O","O","O"],
#                   ["O","O","O","O","O","O","O"],
#                   ["O","O","O","O","O","O","O"],
#                   ["O","O","O","O","O","O","O"]])

boardSize = []
boardSize = input("Enter Your Board Size : ")

a = int(boardSize[0])
b = int(boardSize[1])

if (a<4) : a = 4
if (b<4) : b = 4

board = np.full((a, b), "O")

symbol_O = "\u25CB"
symbol_1 = "\u25CF"
symbol_2 = "\u2717"

printerOutput(board,symbol_O,symbol_1,symbol_2)


turn = input("\nWho wants to Start the Game ? 1/2 : ")
if turn == "1" : turn_1 = True
else : turn_1 = False

while(input):
    
    if turn_1 == True:
        colText_1 = "\nPlayer 1 " + symbol_1 + " : Select a Column : "
        col = int(input(colText_1))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "1"
            turn_1 = False
            
            if checkWinner(board,symbol_O,symbol_1,symbol_2) : break
        else: 
            print('\nInput Error!')
            
    else:
        colText_2 = "\nPlayer 2 " + symbol_2 + " : Select a Column : "
        col = int(input(colText_2))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "2"
            turn_1 = True
            
            if checkWinner(board,symbol_O,symbol_1,symbol_2) : break
        else: 
            print('\nInput Error!')
    printerOutput(board,symbol_O,symbol_1,symbol_2)

Enter Your Board Size : 45
|  ○  |  ○  |  ○  |  ○  |  ○  |   
|  ○  |  ○  |  ○  |  ○  |  ○  |   
|  ○  |  ○  |  ○  |  ○  |  ○  |   
|  ○  |  ○  |  ○  |  ○  |  ○  |   
-------------------------------------------
   0     1     2     3     4     
Who wants to Start the Game ? 1/2 : 2

Player 2 ✗ : Select a Column : 1


TypeError: '<' not supported between instances of 'str' and 'range'

In [ ]:
# print("\u25CF")
# print("\u25CB")
# text = "Ehsan"
# a = "\u25CB"
# print(a)
# a =1
# print(a)
# print('\033[1;32m'+text+'\033[1;m')
# # dayere ghermez:
# print("\033[1;31;40m\u25CF \n")
# print("\033[1;34;40m\u25CF \n")

In [ ]:

# print(np.diag(board , k = 6))
# board2 = board[::-1,:]


# >>> np.diag(x)
# array([0, 4, 8])
# >>> np.diag(x, k=1)
# array([1, 5])
# >>> np.diag(x, k=-1)
# array([3, 7])

In [ ]:
# list1=[1,2,3,4,5,6,7]
# result=""
# for i in list1:
#     result = result + str(i)
# print(result)

In [ ]:
# import numpy as np

# board = np.array([["O","O","O","1","O","O","O"],
#                   ["O","O","O","4","O","8","O"],
#                   ["O","O","7","3","O","O","O"],
#                   ["5","4","O","4","O","O","O"],
#                   ["2","2","3","5","5","6","8"],
#                   ["O","O","O","5","O","O","O"]])

# rows = board.shape[0]
# cols = board.shape[1]
    
    
    
# for i in range(rows):
#     for j in range(cols):
#         if board[i][j] == "O" : board[i][j] = "\u25CB"
#         if board[i][j] == "1" : board[i][j] = "\u25CF"
#         if board[i][j] == "2" : board[i][j] = "X"
# print(board)
            
            

# for i in board:
#         for j in i:
#             if board == "O": board[i][j] = "\u25CB"
# print(board)