In [44]:
def findingTop(board,col):
    if col<(board.shape[1]):
        lc = board.shape[0] -1
        if board[(lc)][col] == "O" : return lc 
        else :
            while board[lc][col] != "O":
                lc = lc-1
                if lc < 0 : 
                    break
            return lc
    else:
        return -1

In [45]:
def printerOutput(board):
    rows = board.shape[0]
    cols = board.shape[1]
    for i in range(rows):
        for j in range(cols):
            if j == 0 : print("| ", end=' ')
            print(board[i][j]," | ", end=' ')
        print(" ")
#         print("\n")
    print("-------------------------------------------")
    print("  ",end=' ')
    for i in range(cols):
        print(i,"   ",end =" ")

In [46]:
def checkInput(board,col):
    cursor = findingTop(board,col)
    if cursor != -1:
        return True
    else: 
        return False

In [31]:
import numpy as np

board = np.array([["O","O","O","1","O","O","O"],
                  ["O","O","O","4","O","8","O"],
                  ["O","O","7","3","O","O","O"],
                  ["5","4","O","4","O","O","O"],
                  ["2","2","3","5","5","6","8"],
                  ["O","O","O","5","O","O","O"]])

rows = board.shape[0]
cols = board.shape[1]

print(rows)
row_list = []
col_list = []
diag1_list = []


                
for i in range(rows):
    rr=[]
    result = ""
    for j in range(cols):
        rr.append(board[i][j])
    for k in rr:
        result = result + str(k)
    row_list.append(result)
print(row_list)



                
for i in range(cols):
    cc=[]
    result = ""
    for j in range(rows):
        cc.append(board[j][i])
    for k in cc:
        result = result + str(k)
    col_list.append(result)
print(col_list)
                

for i in row_list:
    if"73" in i : print("eyvoool")

dd = []
for i in range(cols-3):
    result = ""
    dd.append(np.diag(board, k = i))
    for j in dd:
        result = result + str(j)
    diag1_list.append(result)
    
print(result)
    
# print(np.diag(board , k = 6))



# row5 = b[5][0]+b[5][1]+b[5][2]+b[5][3]+b[5][4]+b[5][5]+b[5][6]
# row4 = b[4][0]+b[4][1]+b[4][2]+b[4][3]+b[4][4]+b[4][5]+b[4][6]
# row3 = b[3][0]+b[3][1]+b[3][2]+b[3][3]+b[3][4]+b[3][5]+b[3][6]
# row2 = b[2][0]+b[2][1]+b[2][2]+b[2][3]+b[2][4]+b[2][5]+b[2][6]
# row1 = b[1][0]+b[1][1]+b[1][2]+b[1][3]+b[1][4]+b[1][5]+b[1][6]
# row0 = b[3][0]+b[3][1]+b[3][2]+b[3][3]+b[3][4]+b[3][5]+b[3][6]

# >>> np.diag(x)
# array([0, 4, 8])
# >>> np.diag(x, k=1)
# array([1, 5])
# >>> np.diag(x, k=-1)
# array([3, 7])

6
['OOO1OOO', 'OOO4O8O', 'OO73OOO', '54O4OOO', '2235568', 'OOO5OOO']
['OOO52O', 'OOO42O', 'OO7O3O', '143455', 'OOOO5O', 'O8OO6O', 'OOOO8O']
eyvoool
['O' 'O' '7' '4' '5' 'O']['O' 'O' '3' 'O' '6' 'O']['O' '4' 'O' 'O' '8']['1' 'O' 'O' 'O']


In [14]:
list1=[1,2,3,4,5,6,7]
result=""
for i in list1:
    result = result + str(i)
print(result)

1234567


In [47]:
import numpy as np

board = np.array([["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"]])
printerOutput(board)


turn = input("\nWho wants to Start the Game ? 1/2 : ")
if turn == "1" : turn_1 = True
else : turn_1 = False

while(True):
    
    if turn_1 == True:
        col = int(input("\nPlayer 1 : Select a Column : "))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "1"
            turn_1 = False
            
#             if checkWinner(board) : break
        else: 
            print('\nInput Error!')
            
    else:
        col = int(input("\nPlayer 2 : Select a Column : "))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "2"
            turn_1 = True
            
#             if checkWinner(board) : break
        else: 
            print('\nInput Error!')
    printerOutput(board)

|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
-------------------------------------------
   0     1     2     3     4     5     6     
Who wants to Start the Game ? 1/2 : 5

Player 2 : Select a Column : 5
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  2  |  O  |   
-------------------------------------------
   0     1     2     3     4     5     6     
Player 1 : Select a Column : 5
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  | 

KeyboardInterrupt: 