In [67]:
def findingTop(board,col):
    if col<(board.shape[1]):
        lc = board.shape[0] -1
        if board[(lc)][col] == "O" : return lc 
        else :
            while board[lc][col] != "O":
                lc = lc-1
                if lc < 0 : 
                    break
            return lc
    else:
        return -1

In [68]:
def printerOutput(board):
    rows = board.shape[0]
    cols = board.shape[1]
    for i in range(rows):
        for j in range(cols):
            if j == 0 : print("| ", end=' ')
            print(board[i][j]," | ", end=' ')
        print(" ")
#         print("\n")
    print("-------------------------------------------")
    print("  ",end=' ')
    for i in range(cols):
        print(i,"   ",end =" ")

In [69]:
def checkInput(board,col):
    cursor = findingTop(board,col)
    if cursor != -1:
        return True
    else: 
        return False

In [72]:
def checkWinner(board):
    rows = board.shape[0]
    cols = board.shape[1]

    board2 = board[::-1,:]
    rows2 = board2.shape[0]
    cols2 = board2.shape[1]

    row_list = []
    col_list = []
    diag1_list = []
    diag2_list = []


    for i in range(rows):
        rr=[]
        result = ""
        for j in range(cols):
            rr.append(board[i][j])
        for k in rr:
            result = result + str(k)
        row_list.append(result)



    for i in range(cols):
        cc=[]
        result = ""
        for j in range(rows):
            cc.append(board[j][i])
        for k in cc:
            result = result + str(k)
        col_list.append(result)



    for i in range(3-cols,cols-3):
        dd = []
        result = ""
        dd.append(np.diag(board, k = i))
        for j in dd:
            result = result + str(j)
        result = result.replace("'", '')
        result = result.replace(" ","")
        result = result.replace("[","")
        result = result.replace("]","")
        diag1_list.append(result)  



    for i in range(3-cols2,cols2-3):
        dd = []
        result = ""
        dd.append(np.diag(board2, k = i))
        for j in dd:
            result = result + str(j)
        result = result.replace("'", '')
        result = result.replace(" ","")
        result = result.replace("[","")
        result = result.replace("]","")
        diag2_list.append(result)

    term_1= "1111"
    winner1 = "Player 1 is Winner"

    for i in row_list:
        if term_1 in i :
            printerOutput(board)
            print(winner1)
            return True
    for i in col_list:
        if term_1 in i :
            printerOutput(board)
            print(winner1)
            return True
    for i in diag1_list:
        if term_1 in i :
            printerOutput(board)
            print(winner1)
            return True
    for i in diag2_list:
        if term_1 in i : 
            printerOutput(board)
            print(winner1)
            return True

    term_2= "2222"
    winner2 = "Player 2 is Winner"

    for i in row_list:
        if term_2 in i : 
            printerOutput(board)
            print(winner2)
            return True
    for i in col_list:
        if term_2 in i : 
            printerOutput(board)
            print(winner2)
            return True
    for i in diag1_list:
        if term_2 in i : 
            printerOutput(board)
            print(winner2)
            return True
    for i in diag2_list:
        if term_2 in i : 
            printerOutput(board)
            print(winner2)
            return True
    if "O" not in table:
        printerOutput(board)
        print("\nDraw')
        return True

In [62]:
import numpy as np

board = np.array([["O","O","O","1","O","O","O"],
                  ["O","O","O","4","O","8","O"],
                  ["O","O","7","3","O","O","O"],
                  ["5","4","O","4","O","O","O"],
                  ["2","2","3","5","5","6","8"],
                  ["O","O","O","5","O","O","O"]])

rows = board.shape[0]
cols = board.shape[1]

board2 = board[::-1,:]
rows2 = board2.shape[0]
cols2 = board2.shape[1]

row_list = []
col_list = []
diag1_list = []
diag2_list = []

                
for i in range(rows):
    rr=[]
    result = ""
    for j in range(cols):
        rr.append(board[i][j])
    for k in rr:
        result = result + str(k)
    row_list.append(result)


                
for i in range(cols):
    cc=[]
    result = ""
    for j in range(rows):
        cc.append(board[j][i])
    for k in cc:
        result = result + str(k)
    col_list.append(result)
    
    
                
for i in range(3-cols,cols-3):
    dd = []
    result = ""
    dd.append(np.diag(board, k = i))
    for j in dd:
        result = result + str(j)
    result = result.replace("'", '')
    result = result.replace(" ","")
    result = result.replace("[","")
    result = result.replace("]","")
    diag1_list.append(result)  

    

for i in range(3-cols2,cols2-3):
    dd = []
    result = ""
    dd.append(np.diag(board2, k = i))
    for j in dd:
        result = result + str(j)
    result = result.replace("'", '')
    result = result.replace(" ","")
    result = result.replace("[","")
    result = result.replace("]","")
    diag2_list.append(result)
    
term_1= "1111"
winner1 = "\nPlayer 1 is Winner"

for i in row_list:
    if term in i : 
        print(winner1)
        break
for i in col_list:
    if term in i : 
        print(winner1)
        break
for i in diag1_list:
    if term in i : 
        print(winner1)
        break
for i in diag2_list:
    if term in i : 
        print(winner1)
        break

term_2= "2222"
winner2 = "\nPlayer 2 is Winner"

for i in row_list:
    if term in i : 
        print(winner2)
        break
for i in col_list:
    if term in i : 
        print(winner2)
        break
for i in diag1_list:
    if term in i : 
        print(winner2)
        break
for i in diag2_list:
    if term in i : 
        print(winner2)
        break


# print(np.diag(board , k = 6))
# board2 = board[::-1,:]


# >>> np.diag(x)
# array([0, 4, 8])
# >>> np.diag(x, k=1)
# array([1, 5])
# >>> np.diag(x, k=-1)
# array([3, 7])

eyvoool


In [14]:
list1=[1,2,3,4,5,6,7]
result=""
for i in list1:
    result = result + str(i)
print(result)

1234567


In [73]:
import numpy as np

board = np.array([["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"],
                  ["O","O","O","O","O","O","O"]])
printerOutput(board)


turn = input("\nWho wants to Start the Game ? 1/2 : ")
if turn == "1" : turn_1 = True
else : turn_1 = False

while(True):
    
    if turn_1 == True:
        col = int(input("\nPlayer 1 : Select a Column : "))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "1"
            turn_1 = False
            
            if checkWinner(board) : break
        else: 
            print('\nInput Error!')
            
    else:
        col = int(input("\nPlayer 2 : Select a Column : "))
        if checkInput(board,col):
            cursor = findingTop(board,col)
            board[(cursor)][col] = "2"
            turn_1 = True
            
            if checkWinner(board) : break
        else: 
            print('\nInput Error!')
    printerOutput(board)

|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
-------------------------------------------
   0     1     2     3     4     5     6     
Who wants to Start the Game ? 1/2 : 1

Player 1 : Select a Column : 0
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  1  |  O  |  O  |  O  |  O  |  O  |  O  |   
-------------------------------------------
   0     1     2     3     4     5     6     
Player 2 : Select a Column : 1
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  |  O  |  O  |  O  |  O  |  O  |   
|  O  |  O  | 